### PR TITLE
stable-baselines3 v1.6.2 fixed

### PR DESCRIPTION
**Pull request by jamesmyatt**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #10

### CODE REVIEW

**Comment by jamesmyatt** [comment]
@conda-forge-admin, please rerender

**Comment by jamesmyatt** [comment]
This is blocked by the lack of the correct version of the import-metadata package on conda-forge: https://github.com/conda-forge/importlib_metadata-feedstock/issues/114

**Review by cyprienc — APPROVED** [review]

**Comment by jamesmyatt** [comment]
@conda-forge-admin Restart CI

**Comment by jamesmyatt** [comment]
@cyprienc . Finally working :tada:

**Comment by traversaro** [comment]
Hello @cyprienc, do you think we can merge? As some months passed, I think we can first restart the CI.

**Comment by traversaro** [comment]
@conda-forge-admin, please restart ci

**Comment by traversaro** [comment]
> Hello @cyprienc, do you think we can merge? As some months passed, I think we can first restart the CI.

The CI is happy, I think this is ready for review, thanks a lot (if you need help mantaining the feedstock I would be happy to help)!

**Comment by YYYasin19** [comment]
@conda-forge/python Is this looking good enough for a merge?

**Comment by ocefpaf** [comment]
> @conda-forge/python Is this looking good enough for a merge?

This is a staged-recipes reviewer team. The maintainers here are responsible for merging PRs in the feedstock.

**Comment by traversaro** [comment]
@YYYasin19 you should be able to merge the PR now, thanks in advance!

**Comment by pavelzw** [comment]
Let's rerender since the last commit is already from a while back

**Comment by pavelzw** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
