### PR TITLE
stable-baselines3 v2.0.0 with additional fixes

### PR DESCRIPTION
**Pull request by traversaro**
Closes: https://github.com/conda-forge/stable-baselines3-feedstock/pull/10
Closes: https://github.com/conda-forge/stable-baselines3-feedstock/pull/12
Closes: https://github.com/conda-forge/stable-baselines3-feedstock/pull/13
Closes: https://github.com/conda-forge/stable-baselines3-feedstock/pull/14

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
After https://github.com/conda-forge/stable-baselines3-feedstock/pull/11 is merged, also this PR is ready for review, thanks!

**Comment by traversaro** [comment]
> After #11 is merged, also this PR is ready for review, thanks!

fyi @YYYasin19 given your interest in the repo.

**Comment by pavelzw** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
